// ==========================================
// Datos Mock para Desarrollo
// ==========================================

import type { Estudiante, Empresa } from "../types";

// Mock de Estudiantes
export const mockEstudiantes: Estudiante[] = [
  {
    id: "1",
    cedula: "1712345678",
    nombreCompleto: "Juan Carlos Pérez Martínez",
    email: "juan.perez@email.com",
    telefono: "+593 2 2345678",
    direccion: "Av. Amazonas N34-451 y Av. Atahualpa, Quito",
    carrera: "Desarrollo y administración de aplicaciones informáticas",
    semestre: 6,
    promedioGeneral: 8.5,
    estado: "Activo",
    fechaIngreso: "2022-03-15",
    identidadTitulo: "Desarrollo y administración de aplicaciones informáticas",
    codigoTitulo: "IFC006_3",
    horario: "Lunes a Viernes 8:00-14:00",
  },
  {
    id: "2",
    cedula: "1723456789",
    nombreCompleto: "María Gabriela Torres López",
    email: "maria.torres@email.com",
    telefono: "+593 2 3456789",
    direccion: "Calle La República 123, Quito",
    carrera: "Desarrollo y administración de aplicaciones informáticas",
    semestre: 8,
    promedioGeneral: 9.2,
    estado: "Activo",
    fechaIngreso: "2021-09-20",
    identidadTitulo: "Desarrollo y administración de aplicaciones informáticas",
    codigoTitulo: "IFC006_3",
    horario: "Lunes a Viernes 14:00-20:00",
  },
  {
    id: "3",
    cedula: "1734567890",
    nombreCompleto: "Andrés Felipe Sánchez Castro",
    email: "andres.sanchez@email.com",
    telefono: "+593 2 4567890",
    direccion: "Av. La Pampa 456, Quito",
    carrera: "Desarrollo y administración de aplicaciones informáticas",
    semestre: 4,
    promedioGeneral: 7.8,
    estado: "Activo",
    fechaIngreso: "2023-01-10",
    identidadTitulo: "Desarrollo y administración de aplicaciones informáticas",
    codigoTitulo: "IFC006_3",
    horario: "Lunes a Viernes 8:00-14:00",
  },
  {
    id: "4",
    cedula: "1745678901",
    nombreCompleto: "Ana Sofía Vargas Molina",
    email: "ana.vargas@email.com",
    telefono: "+593 2 5678901",
    direccion: "Av. Galo Plaza Lasso 789, Quito",
    carrera: "Desarrollo y administración de aplicaciones informáticas",
    semestre: 10,
    promedioGeneral: 9.5,
    estado: "Activo",
    fechaIngreso: "2020-08-15",
    identidadTitulo: "Desarrollo y administración de aplicaciones informáticas",
    codigoTitulo: "IFC006_3",
    horario: "Lunes a Viernes 14:00-20:00",
  },
  {
    id: "5",
    cedula: "1756789012",
    nombreCompleto: "Carlos Eduardo Jiménez Benítez",
    email: "carlos.jimenez@email.com",
    telefono: "+593 2 6789012",
    direccion: "Calle 10 de Agosto 321, Quito",
    carrera: "Desarrollo y administración de aplicaciones informáticas",
    semestre: 2,
    promedioGeneral: 8.0,
    estado: "Activo",
    fechaIngreso: "2023-09-01",
    identidadTitulo: "Desarrollo y administración de aplicaciones informáticas",
    codigoTitulo: "IFC006_3",
    horario: "Lunes a Viernes 8:00-14:00",
  },
];

// Mock de Empresas
export const mockEmpresas: Empresa[] = [
  {
    id: "1",
    ruc: "123456789001",
    razonSocial: "Tecnologías Innovadoras S.A.",
    nombreComercial: "TechInnovate",
    tipoEmpresa: "Empresa Privada",
    sector: "Tecnología",
    tamano: "Mediana (51-200)",
    estado: "Activo",
    telefono: "+593 2 2345678",
    email: "contacto@techinnovate.com",
    website: "www.techinnovate.com",
    direccion: "Av. Amazonas N34-451 y Av. Atahualpa",
    ciudad: "Quito",
    provincia: "Pichincha",
    contactos: [
      {
        id: "1",
        nombre: "Carlos Rodríguez",
        cargo: "Gerente de RRHH",
        email: "c.rodriguez@techinnovate.com",
        telefono: "+593 2 2345678",
        extension: "101",
        esPrincipal: true,
      },
    ],
    descripcion: "Empresa especializada en desarrollo de software y soluciones tecnológicas",
    servicios: "Desarrollo de software a medida, consultoría TI, soporte técnico",
    productos: "Sistema de gestión ERP, aplicaciones móviles",
    anosOperacion: 8,
    representanteLegal: "María González",
    cedulaRepresentante: "1712345678",
    cantidadPracticas: 5,
    cantidadPracticasActivas: 2,
    ultimaPractica: "2024-02-15",
    observaciones: "Excelente empresa para prácticas de desarrollo de software",
  },
  {
    id: "2",
    ruc: "987654321001",
    razonSocial: "Hospital General del Norte",
    nombreComercial: "HGN",
    tipoEmpresa: "Institución Educativa",
    sector: "Salud",
    tamano: "Grande (201+)",
    estado: "Activo",
    telefono: "+593 2 3456789",
    email: "rrhh@hgn.edu.ec",
    website: "www.hgn.edu.ec",
    direccion: "Av. La Patria 123",
    ciudad: "Ibarra",
    provincia: "Imbabura",
    contactos: [
      {
        id: "1",
        nombre: "Dra. Ana Martínez",
        cargo: "Directora de Enfermería",
        email: "a.martinez@hgn.edu.ec",
        telefono: "+593 2 3456789",
        extension: "201",
        esPrincipal: true,
      },
    ],
    descripcion: "Hospital de tercer nivel especializado en atención médica integral",
    servicios: "Atención médica, emergencias, cirugías especializadas",
    productos: "Servicios de salud",
    anosOperacion: 25,
    representanteLegal: "Dr. Luis Torres",
    cedulaRepresentante: "1719876543",
    cantidadPracticas: 12,
    cantidadPracticasActivas: 4,
    ultimaPractica: "2024-02-28",
    observaciones: "Centro de prácticas excelente para estudiantes de enfermería y medicina",
  },
  {
    id: "3",
    ruc: "456789123001",
    razonSocial: "Manufacturas Andinas Cía. Ltda.",
    nombreComercial: "Andina Manufacturing",
    tipoEmpresa: "Empresa Privada",
    sector: "Manufactura",
    tamano: "Pequeña (11-50)",
    estado: "Activo",
    telefono: "+593 3 4567890",
    email: "info@andinamfg.com",
    direccion: "Km 8 vía a Daule",
    ciudad: "Guayaquil",
    provincia: "Guayas",
    contactos: [
      {
        id: "1",
        nombre: "Roberto Sánchez",
        cargo: "Gerente de Producción",
        email: "r.sanchez@andinamfg.com",
        telefono: "+593 3 4567890",
        esPrincipal: true,
      },
    ],
    descripcion: "Empresa dedicada a la manufactura de productos textiles",
    servicios: "Producción textil, diseño industrial",
    productos: "Ropa deportiva, uniformes industriales",
    anosOperacion: 12,
    representanteLegal: "Patricia López",
    cedulaRepresentante: "1745678901",
    cantidadPracticas: 3,
    cantidadPracticasActivas: 1,
    ultimaPractica: "2024-01-20",
    observaciones: "Buena opción para prácticas de ingeniería textil y diseño",
  },
];
